apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gitlab.fullname" . }}
  labels:
    {{- include "gitlab.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "gitlab.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "gitlab.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "gitlab.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          ## General GitLab Configs
          ##
          # This is a free-form env var that GitLab Omnibus uses to configure
          # everything. We're passing this in from a configmap and pulling some
          # of the values from the env vars defined below. This is done to
          # avoid leaving secrets visible in kubectl.
          - name: GITLAB_ROOT_PASSWORD
            {{- if default "" .Values.gitlabRootPassword }}
            valueFrom:
              secretKeyRef:
                name: {{ template "gitlab.fullname" . }}
                key: gitlab-root-password
            {{ end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /help
              port: http
            initialDelaySeconds: 600
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /help
              port: http
            initialDelaySeconds: 600
            periodSeconds: 60
          volumeMounts:
          - name: {{ template "gitlab.fullname" . }}-etc
            mountPath: /etc/gitlab
          resources:
{{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
{{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: gitlab-etc
        {{- if .Values.persistence.gitlabEtc.enabled }}
          persistentVolumeClaim:
            claimName: {{ template "gitlab.fullname" . }}-etc
        {{- else }}


  {{- end}}
