apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.name" . }}-password
  labels: {{ include "app.labels" . | indent 4 }}
type: Opaque
data:
  db-password: {{ .Values.postgresql.password | b64enc | quote }}
