apiVersion: v1
kind: Service
metadata:
  name: {{ template "app.name" . }}
  labels: {{ include "app.labels" . | indent 4 }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: service
  selector: {{ include "app.selector" . | indent 4 }}
