apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ template "app.name" . }}
  labels: {{ include "app.labels" . | indent 4 }}
spec:
  host: {{ .Values.ingress.host }}
  to:
    kind: Service
    name: {{ template "app.name" . }}
    weight: 100
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
status:
  ingress: []