apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app.name" . }}-tls-config
  labels: {{ include "app.labels" . | indent 4 }}
data:
  server.xml: |-
    <Server port="8015" shutdown="SHUTDOWN">
      <Service name="Catalina">
        <Connector port="8081"
            sendReasonPhrase="true"
            protocol="HTTP/1.1"
            SSLEnabled="true"
            maxThreads="150"
            minSpareThreads="25"
            maxSpareThreads="75"
            enableLookups="false"
            disableUploadTimeout="true"
            acceptCount="100"
            scheme="https"
            secure="true"
            clientAuth="false"
            sslProtocol="TLS"
            keystoreFile="{{ .Values.storage.mountPath }}/webapp.jks"
            keystorePass="tomcat" />
{{- if .Values.docker.enabled }}
      <Connector port="8082"
            sendReasonPhrase="true"
            protocol="HTTP/1.1"
            SSLEnabled="true"
            maxThreads="150"
            minSpareThreads="25"
            maxSpareThreads="75"
            enableLookups="false"
            disableUploadTimeout="true"
            acceptCount="100"
            scheme="https"
            secure="true"
            clientAuth="false"
            sslProtocol="TLS"
            keystoreFile="{{ .Values.storage.mountPath }}/docker.jks"
            keystorePass="tomcat" />
{{- end }}
        <Connector port="8040" sendReasonPhrase="true" maxThreads="50"/>
        <Connector port="8019" protocol="AJP/1.3" sendReasonPhrase="true"/>
        <Engine name="Catalina" defaultHost="localhost">
          <Host name="localhost" appBase="webapps" startStopThreads="2">
            <Context path="" crossContext="true" docBase="${artifactory.home}/webapps/artifactory.war" processTlds="false">
              <Manager pathname="" />
            </Context>
          </Host>
        </Engine>
      </Service>
    </Server>
